### ISSUE TITLE
Summary statistics columns

### ISSUE THREAD

**Issue by karpat90** [molepi-precmed/mrhevo#4]
Hello!

I have another question. I am using the latest version mr_hevo. The columns of outcome summary statistics in the tutorial https://molepi-precmed.github.io/mrhevo/pages/vignette.html and example dataset (coeffs.dt.rda) are different. In the tutorial, they are beta_YZ and SE_YZ, while in the example dataset from github they are name gamma_hat, se.gamma_hat. Moreover, when I use function estimators.dt=get_estimatorsMR(coeffs.dt)[, 1:5] on example dataset, I get error:
Error in eval(jsub, SDenv, parent.frame()) : object 'theta_IV' not found

Error in eval(jsub, SDenv, parent.frame()) : object 'inv.var' not found

I therefore renamed the columns in coeffs.dt from "thetaIV" to "theta_IV", and changed "se.thetaIV" to "inv.var". In the tutorial, "thetaIV" and "se.thetaIV"  are also used, even though get_estimatorsMR function seems to look for other names.  It also would be great, if the calculation of theta_IV_delta was provided in the tutorial.  Additionally, I wonder if several genes and their respecitve pQTLs can be used in the MR analyses, similar to TwoSampleMR, where you can use several exposures to run with particular outcome. I am currently running analyses on multiple deCODE gene cis-pQTLs  and woder if it would be better to run analyses for each gene seperately, since mrhevo function get_estimatorsMR, provides a single estimate for each MR test. Many thanks for you help! I really appreciate your assistance.

**Comment by whimsial** [comment]
Thank you for reporting the bug in the column names in the example data `coeffs.dt`! I have now corrected these names to "theta_IV", "se.theta_IV_delta", "size.theta_IV", "se.theta_IV" (see #5). If you recompile the package from `main` brunch this issue should be removed.

If you want to compute the classical MR estimators on the example data you could do the following:

```r
library(mrhevo)
data(coeffs.dt)

## compute ratios of coefficients on exposure and outcome and add `inv.var` column
coeffs.dt <- get_coeffratios(coeffs.dt)

## compute estimators
estimators.dt <- get_estimatorsMR(coeffs.dt)
```

What I get from the above is the following data.table with estimators from 3 common methods:

```
                   Estimator   Estimate         SE          z       pvalue
                      <char>      <num>      <num>      <num>        <num>
1:             Weighted mean -0.3001549 0.01959926 -15.314602 6.108480e-53
2:           Weighted median -0.2551593 0.04024444  -6.340236 2.294130e-10
3: Penalized weighted median -0.3031743 0.04063265  -7.461348 8.564193e-14
                   pvalue.formatted
                             <char>
1: \\ensuremath{6 \\times 10^{-53}}
2: \\ensuremath{2 \\times 10^{-10}}
3: \\ensuremath{9 \\times 10^{-14}}
```

Regarding the discrepancies with the vignette. It was created by Paul prior to the package and I did not have time to correct it. I created a separate issue for that (#6) and will look at it as soon as I can.

I would discourage you from running MR either conventional estimators of mrhevo only on cis-pQTLs. The reason being that you will not have sufficient number of instruments to make inference. I'd recommend to include both cis and trans pQTLs or just trans-pQTLs which should give you at least a dozen instruments -- the minimal number of this sort of inference.

Finally, we dont currently provide a way of running MR for multiple exposures concurrently. You would need to run mrhevo in for loop over you proteins of interest and then combine the results. You can also run several exposures in parallel using `foreach`. This will be quite fast.

Let me know is this answers your questions?

**Comment by karpat90** [comment]
Thank you for a detailed reply and fixing the bug! Indeed some of deCODE genes only have one cis-pQTL as an instrument; this is probably the reason why run_mrhevo.sstats fails for them. I agree with you that we cannot make an adequate assessment of causal relationship using a limited number of IVs.

**Comment by whimsial** [comment]
Correct. Is it OK to close this issue now?

**Comment by karpat90** [comment]
I have downloaded devtools::install_github(repo="molepi-precmed/mrhevo", ref="main"), but the issue persists: estimators.dt <- get_estimatorsMR(coeffs.dt[qtl_type=="trans"])[, 1:5] 
Error in eval(jsub, SDenv, parent.frame()) : object 'theta_IV' not found

**Comment by whimsial** [comment]
Cam you try it without subsetting the columns?

```
estimators.dt <- get_estimatorsMR(coeffs.dt[qtl_type=="trans"])
```

**Comment by karpat90** [comment]
Yes, it works now, thank you, after I used get_coeffratios.

**Comment by karpat90** [comment]
I wanted to ask if I want to run a loop for different genes, should I set:
 use.sampling <- TRUE
logistic <- TRUE
priorsd_theta <- 1
_**newrun <- TRUE** ?_

Thank you!

**Comment by whimsial** [comment]
> I wanted to ask if I want to run a loop for different genes, should I set: use.sampling <- TRUE logistic <- TRUE priorsd_theta <- 1 _**newrun <- TRUE** ?_
> 
> Thank you!

I think `newrun` parameter is not used anymore. You can see a full script to run an analysis for a single exposure using the example data here: https://github.com/molepi-precmed/mrhevo/blob/main/man/examples/runmrhevo.R

You can rework it to make a loop over exposures.

**Comment by karpat90** [comment]
Thank you! I appreciate your help!

**Comment by whimsial** [comment]
The required changes to the vignette will be addressed in #6. Closing this issue as resolved.
